export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
  return (
    <>
      <div className="bg-teal-500">{children}</div>
    </>
  );
};

export default DashboardLayout;
